### ISSUE TITLE
resolve to a Container error.

### ISSUE THREAD

**Issue by taffo73** [trossr32/ps-transmission#19]
Update-Help: Failed to update Help for the module(s) 'Transmission' with UI culture(s) {en-US} : The value of the HelpInfoUri key in the module manifest must resolve to a container or root URL on a website where the help files are stored. The HelpInfoUri 'https://github.com/trossr32/ps-transmission' does not resolve to a container..
English-US help content is available and can be installed using: Update-Help -UICulture en-US.
Update-Help: Failed to update Help for the module(s) 'AutoSequencer, ConfigDefenderPerformance, Dism, Get-NetView, Kds, NetQos, Pester, PKI, Whea, WindowsUpdate' with UI culture(s) {en-US} : One or more errors occurred. (Response status code does not indicate success: 404 (The specified blob does not exist.).).
English-US help content is available and can be installed using: Update-Help -UICulture en-US.

**Comment by trossr32** [comment]
Try: https://stackoverflow.com/a/73523664/608346

**Comment by taffo73** [comment]
still the same error

**Comment by trossr32** [comment]
Out of interest why are you trying to call `Update-Help`? The module is compiled with the latest help files before it's published to the Powershell Gallery so as long as you have the latest version of the module, you'll have the latest version of the help. 

I think it's actually because `Update-Help` expects there to be some help files online and because this is a Powershell Cmdlet written in C#, the help files look like [this](https://github.com/trossr32/ps-transmission/blob/master/src/PsTransmission/Transmission.dll-Help.xml) in their raw state. 

`Get-Help` works fine for me:

![image](https://github.com/trossr32/ps-transmission/assets/332954/72710032-a5f0-421b-8121-37c140354a29)

@BanterBoy is `Update-Help` something you use? Would you expect the command to do something for all modules?

**Comment by trossr32** [comment]
Run: 

`Get-Module -ListAvailable -Name Transmission`

If your version is 1.1.0 then you have the latest version and help. If not, run:

`Update-Module -Name Transmission`

and you should be good to go

**Comment by trossr32** [comment]
Luke just mentioned you wanted to use help to see how to set up creds. There's a guide for that in the README you can follow mate: https://github.com/trossr32/ps-transmission?tab=readme-ov-file#supplying-api-credentials

**Comment by taffo73** [comment]
All good, it's working as it should now, appreciate your help bud.
